-- Create an Enum for Car Status
create type car_status as enum ('LOST', 'FOUND');

-- Create the Cars table
create table public.cars (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  make text not null,
  model text not null,
  year int,
  color text,
  license_plate text,
  status car_status not null,
  description text,
  contact_info text,
  image_url text
);

-- Enable Row Level Security (RLS)
alter table public.cars enable row level security;

-- Policies

-- 1. Allow public read access to all cars (since it's a lost & found app)
create policy "Enable read access for all users"
on public.cars for select
using (true);

-- 2. Allow public insert access (so anyone can report a car for now)
-- Note: In a production app, you might restrict this to authenticated users
create policy "Enable insert for all users"
on public.cars for insert
with check (true);

-- 3. Allow updates only if you created it? (Skipping complex logic for MVP, allowing public updates for now or restricting)
-- Let's just allow inserts and reads for the MVP as per "list lost and found cars" and "search".
